apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::384889829505:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-LVTXA433BD6N
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-18T20:12:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1514"
  uid: 44f1a7d3-70c3-41e6-befa-24629c857110
