"""Artist update

Revision ID: 11722a5baa78
Revises: 66848f063cba
Create Date: 2022-01-25 22:10:03.060824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11722a5baa78'
down_revision = '66848f063cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
